[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cloud_sol_treasury = "CEbZve3kn48J3sdsNhiET35d93F5ydCEbgEVKCLr6oGX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
